---
- name: Install Cord tester prerequisites
  become: yes
  apt: name={{ item }} state=latest force=yes
  with_items:
    - wget
    - python
    - python-dev
    - python-pip
    - python-setuptools
    - python-scapy
    - python-pexpect
    - openvswitch-switch

- name: Install Python Prerequisites for cord tester
  become: yes
  pip: name={{ item }} state=latest
  with_items:
    - nose
    - scapy
    - monotonic
    - configObj
    - docker-py
    - pyyaml
    - nsenter
    - pyroute2
    - netaddr
    - python-daemon
    - scapy-ssl_tls

- name: install Pipework
  sudo: True
  get_url:
    url: "{{ docker_tools_pipework_exe_url }}"
    dest: "{{ docker_tools_path }}/pipework"
    force: yes
    mode: "a+x"

- name: Pull cord test container
  become: yes
  docker:
    name: cord-test
    image: "{{ docker.registry }}/cord-test/nose:{{ docker.image_version }}"
    pull: always
    state: absent

- name: Pull test radius container
  become: yes
  docker:
    name: cord-radius
    image: "{{ docker.registry }}/cord-test/radius:{{ docker.image_version }}"
    pull: always
    state: absent

- name: Pull test quagga container
  become: yes
  docker:
    name: cord-quagga
    image: "{{ docker.registry }}/cord-test/quagga:{{ docker.image_version }}"
    pull: always
    state: absent
